# blog settings
title: Florent Cailhol
analytics_account: UA-58564722-1
disqus_account: ooflorent

# build settings
exclude: ["Gemfile", "Gemfile.lock"]
highlighter: pygments
markdown: redcarpet
permalink: /:title/